### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by MattRCole** [lexica/web-lexica#6]
One of the best parts of Lexica is that it has a large toolset to allow the extension of the game via translations of in-game text, additions of new languages to play games in, etc.

Unfortunately, on the web side of things, the app is only usable in one language: `English`.

A way to leverage the translations made for `Lexica` in `Web Lexica` should be considered. However, if this isn't done carefully, really crappy inter-dependencies between the apps could be created.

Let's discuss the following:

- Should `Web Lexica` try to use the same translations that `Lexica` uses
- If it should, what's a good way to go about using them

**Comment by MattRCole** [comment]
I feel like the web app should use the translations from the android app. There's a lot of work that's gone into making them, and, on the `JavaScript` side of things, it shouldn't be too hard to use them: there are a lot of packages out there for parsing `XML`, or they could be released in both `JSON` and  `XML` formats

The tricky part in my opinion is the interdependencies between the two apps that would create. In the future, if either apps were expanded in some way (say, a completely new game mode), then there could be breaking changes for one of the two apps until they are both in sync again.

**Comment by MattRCole** [comment]
#7 Shows one possible solution to this, but it's not a very good solution. If translations were implemented exactly like this, `Web Lexica` would have a dependency on `Lexica`.

@pserwylo any thoughts?

**Comment by pserwylo** [comment]
Hey, sorry for the delay (starting a new job today). Comment left in #7.

**Comment by MattRCole** [comment]
With the weblate project, I think we are good to close this issue for now
